language: python

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

env:
  - CXX="g++-4.8" CC="gcc-4.8"

python:
  - "2.7"

install:
  - pip install .

script:
  - python setup.py build
  - python setup.py install
