language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.8;
  - export CXX="g++-4.8";
  
  - pip install .
script:
  - python setup.py build
  - python setup.py install
