from numpy.distutils.core import setup

def generate_lut(filename):
        from tpmc.lut.lutgen.dunecode import DuneCode
        print "importing lookup generators"
        from tpmc.lut.lutgen.base_case_triangulation import LookupGenerators
        ## geometries of LookupGenerators
        geometries = [(0,"any"),
                      (1,"any"),
                      (2,"simplex"), (2,"cube"),
                      (3,"simplex"), (3,"prism"), (3,"pyramid"), (3,"cube")]
        ## Output C code
        ccfile = open(filename, "w")
        ccfile.write("""
    /*
     * This file is autogenerated using generate_lut.py
     *
     * Don't edit this file!
     */

#include "marchinglut.hh"

extern \"C\" {

""")
        for g in geometries:
                print "generating table for %id %s" % g
                generator = LookupGenerators[g]['standard']
                generator.generate()
                print "writing code for %id %s" % g
                DuneCode(generator).write(ccfile)
        g = (3,'cube')
        print "generating symmetric table for %id %s" % g
        generator = LookupGenerators[g]['symmetric']
        generator.generate()
        print "writing symmetric code for %id %s" % g
        DuneCode(generator, 'sym').write(ccfile)
        ccfile.write("}\n")
        ccfile.close()

def configuration(parent_package='', top_path=None):
        import numpy
        from numpy.distutils.misc_util import Configuration
        config = Configuration('pytpmc',parent_package,top_path)
        lutfile = 'build/marchinglut.cc'
        generate_lut(lutfile)
        config.add_installed_library('marchinglut',
                                     sources = [lutfile],
                                     install_dir = 'lib',
                                     build_info = {
                                             'include_dirs' : [ 'tpmc/lut' ]
                                     })
        # config.add_installed_library(..., install_dir='../..') to install in /usr/local/lib
        return config

setup (name = 'tpmc',
       version = '1.0',
       description = 'python classes to generate TPMC lookup tables',
       author = 'Christian Engwer',
       author_email = 'christi@mathe-macht-spass.de',
       url = 'https://docs.python.org/extending/building',
       long_description = '''
       Implementation of the topology preserving marching cubes.
       ''',
       configuration=configuration
)
