#!/usr/bin/python

import tpmc
import tpmc.__version__
import argparse

parser = argparse.ArgumentParser(prog='tpmc-config')
parser.add_argument('--cflags', const="-I@incdir@",
                    action='append_const', dest='output',
                    help='print pre-processor and compiler flags')
parser.add_argument('--libs', const="-L@libdir@ -ltpmc_tables",
                    action='append_const', dest='output',
                    help='print library linking information')
parser.add_argument('--version', version=tpmc.__version__.__version__,
                    action='version', dest='output',
                    help='output version information')

args = parser.parse_args()
if args.output:
    print " ".join(args.output)
